// <auto-generated />
namespace ForMen.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _03UserCartOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_03UserCartOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "201705131859214_03-UserCartOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
