// <auto-generated />
namespace SportShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _09WishList : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_09WishList));
        
        string IMigrationMetadata.Id
        {
            get { return "201705272331317_09-WishList"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
