// <auto-generated />
namespace SportShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _05ProductFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_05ProductFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201705140056051_05-ProductFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
